### PR TITLE
added screenshot

### PR DESCRIPTION
**Pull request by udpsunil**
I have added wingpanel-indicator screenshot for keyboard as mentioned in the issue #53

### CODE REVIEW

**Comment by udpsunil** [comment]
Does this look fine?
screenshot

**Comment by bumper314** [comment]
Also, to match the convention of the other wingpanel-indicator repos, you could:

1) Use HiDPI mode.
2) Center the wingpanel and make the screenshot 1500px wide (this will give you large margins on both sides, but that's how the other screenshots look too).

**Comment by udpsunil** [comment]
1. How do I use HiDPI mode?

**Comment by ryonakano** [comment]
@udpsunil I guess selecting "Pixel Doubled" should enable HiDPI mode.

**Comment by udpsunil** [comment]
I set pixel doubled and now I'm unable to login to my laptop. Screen is
blank. I'm reinstalling the OS again. With my laptop, I guess I cannot
provide you what you need. Sorry about that.

Regards,
Sunil

**Comment by ryonakano** [comment]
@udpsunil I'm sorry that what I suggested causes issues on your laptop and made you reinstall the system.

**Comment by danrabbit** [comment]
It looks like someone else was able to make the changes in #55 and it was merged. Thanks for your effort working on this!

**Pull request closed without merging**
